# This workflow will filter PR workflow runs when a new one gets started and avoid running same task twice 

name: Cancel Redundant PR Builds

on: [pull_request]

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: 5127767
          access_token: ${{ github.token }}
